### ISSUE TITLE
add ability to define optional timestamp range

### ISSUE THREAD

**Issue by thegostep** [flashbots/ethers-provider-flashbots-bundle#1]
see rpc interface defined here: 
https://github.com/flashbots/mev-geth/blob/91c3b1128c503fcf2cc473910c61bb2237a95c97/core/mev_bundle.go#L25-L30

**Comment by epheph** [comment]
@jparyani this just provides a hint to the miner that the bundle is only valid within that window?

I wonder if i could also use that data to perform a simulation before a block is mined.

**Comment by thegostep** [comment]
taking a crack at this today
