### ISSUE TITLE
sendPrivateTransaction fast mode deprecated?

### ISSUE THREAD

**Issue by pixelpawnshop** [flashbots/ethers-provider-flashbots-bundle#109]
Is transaction speed parameter for sendPrivateTransaction deprecated?

` fast: boolean,  // Deprecated; required until this is removed from the API. Value has no effect.`

Why is that? 

Is there a other way to make sure the transaction gets not only found by flashbot builder but all? 

Thanks in advance!

**Comment by sakulstra** [comment]
hey @pixelpawnshop, just curios what was the solution/answer to that 😅

**Comment by pixelpawnshop** [comment]
@sakulstra 

Hey there I used sendBundle instead. Then you have to  send each bundle to all builders if you want the tx to go through as fast as possible. 

https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint#mev_sendbundle
