### ISSUE TITLE
Uncapped `maxTimestamp` value

### ISSUE THREAD

**Issue by sambacha** [flashbots/ethers-provider-flashbots-bundle#11]
Currently `maxTimestamp` is only defined as a number 

```typescript
export interface FlashbotsOptions {
--
  | minTimestamp?: number,
  | maxTimestamp?: number
  | }
```
without restriction / upper-bound value on 'maxTimestamp malicious transaction submissions could fill the pool, making it necessary to manually flush said transactions out. 

This is sort of similar to how 3rd Party service providers, e.g. Infura, limit transactions to within a certain threshold of some parameters, such as Gas Pricing, in an effort to prevent malicious transaction submission (i.e. DDoS). 

Should some value be encoded? Should it be an equation or simply some number of blocks chosen? Is this sort of thing out of scope for MEV? 

Cheers

**Comment by jparyani** [comment]
I think this is out of scope for the client library. There is going to be some limit, but it is enforced at the relay level, and may be dynamic based on load or other factors.
